vim.keymap.set("n", "<leader>ff", "<cmd>FzfLua files<CR>")
vim.keymap.set("n", "<leader>fo", "<cmd>FzfLua oldfiles<CR>")
vim.keymap.set("n", "<leader>fg", "<cmd>FzfLua git_files<CR>")
vim.keymap.set("n", "<leader>/", "<cmd>FzfLua live_grep<CR>")
vim.keymap.set("n", "<leader>*", "<cmd>FzfLua grep_cword<CR>")
vim.keymap.set("v", "<leader>*", "<cmd>FzfLua grep_visual<CR>")
vim.keymap.set("n", "<leader>fzf", "<cmd>FzfLua builtin<CR>")
